name = "core-stack"
version = "1.0.0"
type = "nebula"
description = "A simulation of a nebula"
install_script = "install.lua"

[authors]
afroraydude = "afroraydude@protonmail.com"

[dependencies]
hello = "1.0.0"
